### ISSUE TITLE
AMOLED black theme

### ISSUE THREAD

**Issue by rootsh0pf** [yuttadhammo/BodhiTimer#100]
Could you please bring back the all black background, maybe as an option? On an AMOLED display it imho looks nicer and even saves some power.
Thank you for this very useful app, I use it daily. :)

**Comment by tzugen** [comment]
Will come in 6.1.3, which I just released

**Comment by MrJberg** [comment]
Thanks for the great black background. Please note that you have to restart the app for it to take effect.

**Comment by rootsh0pf** [comment]
Yes, thank you very much! Only the top bar is still grey, not completely black. But that's a very minor problem ;)
