### ISSUE TITLE
Widget show nothing.

### ISSUE THREAD

**Issue by tumashu** [yuttadhammo/BodhiTimer#106]
Today, I try to add bodhiTimer widget to my desktop of phone, 
the problem is that the widget show nothing,  how to deal with 
this problem?

**Comment by tumashu** [comment]
![Screenshot_20221128_134236](https://user-images.githubusercontent.com/67725/204202679-e86d1c4d-08c3-4897-bf54-89ce0678640b.jpg)

the widget is exist, but do not show some info.

**Comment by MrJberg** [comment]
Same here. Using OnePlus 9 Pro, Android 13, All English.

**Comment by tumashu** [comment]
I think it not work now, for the code is commented :-)

```
    private fun doTick() {

//        if (widgetIds.length == 0)
//            return;
//
//        views = new RemoteViews(mContext.getPackageName(), R.layout.appwidget);
//
//        Bitmap bmp = originalBitmap;
//
//        views.setImageViewBitmap(R.id.mainImage, bmp);
//
//        // Tell the widget manager
//        for (int widgetId : widgetIds) {
//            // set background
//            views.setImageViewResource(R.id.backImage, themeId);
//            appWidgetManager.updateAppWidget(widgetId, views);
//        }
    }
```

**Comment by tzugen** [comment]
Should be fixed in master branch!
