### ISSUE TITLE
Add sound when timer ends

### ISSUE THREAD

**Issue by zoroya1** [yuttadhammo/BodhiTimer#122]
There is sound option for starting of meditation and for timer, but there is no sound when one completes meditations, it might be helpful to play a sound when timer ends, so user can be aware of that.

**Comment by Solomon1732** [comment]
There is. It's called Timer Sound. It's in the preferences.
![1000014637](https://github.com/yuttadhammo/BodhiTimer/assets/16454223/b3891d8b-1820-4876-a6ed-8a513ecc0dd5)
