### ISSUE TITLE
Alarm issues on Android 6+

### ISSUE THREAD

**Issue by dalb8** [yuttadhammo/BodhiTimer#13]
In Android 6 it seems that the system kills Bodhi Timer before it can complete the timer. I even have  Battery Optimization disabled in Settings. This is most obvious when using many continuous timers. I've noticed this on stock LG G4 with Android 6 and also a custom ROM on Android 7.

**Comment by tzugen** [comment]
It should be fixed now, in version 5.0.0, which will be soon available on F-Droid
