### ISSUE TITLE
multiple timers stop even when they should continue

### ISSUE THREAD

**Issue by davidedelvento** [yuttadhammo/BodhiTimer#14]
This may be related to #2 
Simpler step to reproduce (I have to try with shorter durations to see if it happens)

40s
20s
40s
20s
40s
25s
1m

Almost always at the first run it works. When it finishes, I manually re-run it. At the second or third run it will usually stop at one of the transitions instead of completing the whole thing to the final 1m. In the rare cases in which the 3 runs all work, closing the app, reopening it and retrying 3 times have only produced the bug.

Factory unlocked Samsung J3 with Android v6

**Comment by davidedelvento** [comment]
This still happens all the time for me.

@afanfa

**Comment by tzugen** [comment]
I have completely rewritten the way Alarms are handled, and this should be fixed now (in version 5.2.0)
