### ISSUE TITLE
Bell sounds too early

### ISSUE THREAD

**Issue by oskarkv** [yuttadhammo/BodhiTimer#16]
I set Bodhi Timer for 60 minutes and started it. I noted the time on a separate clock. When Bodhi Timer's bell sounded, I checked the other clock. 59 minutes had elapsed. When I checked Bodhi Timer it was still counting down with 1 min 30 seconds left. The bell sounded too early! Even Bodhi timer itself is still counting down. I have had this happen several times. I had the phone in standby mode (screen turned off, etc) during meditation.

**Comment by tzugen** [comment]
I have completely rewritten the way Alarms are handled, and this should be fixed now (in version 5.2.0)
