### ISSUE TITLE
timer keeps running while commanded to stop

### ISSUE THREAD

**Issue by joethelion** [yuttadhammo/BodhiTimer#2]
Using the timere in auto-reload mode, it happens that timer keeps running while it has been manually stopped. Despite the widget showing no countdown, despite the app itself showing no countdown, the bell keeps ringing at interval defined for last timer use.
This is solved by running the timer and stopping it again.
THis is an issue that I have experienced several times, however not been able to find how to reproduce it, not been able to find causes to it.

**Comment by joethelion** [comment]
Unfortunately, I've been unable to find a way to reproduce this behavior. It happens from once a week to once a month.
Have you worked on it somehow? I recently (two days ago) updated to latest version and found that auto-reload was not working, i.e. option is checked and timer runs only once, in the following cases:
- lusing preset timings
- using long period of times, it appears not to work for 1 minute and more, but did auto-reload for 20seconds and less.

By the way great improvement to have this 'adv' section. When the auto-reload is working on that too, that will make a perfect mindfullness bell .

**Comment by tzugen** [comment]
I have completely rewritten the way Alarms are handled, and this should be fixed now (in version 5.2.0)
