### ISSUE TITLE
Preset timer malfunction

### ISSUE THREAD

**Issue by Karena-valentine** [yuttadhammo/BodhiTimer#24]
The "ADV" button on the preset timers bar isn't working. It used to take you to edit the preset timers, but now it starts the countdown from whatever your last time entered was. There is currently no way to edit the preset timers.

**Comment by tzugen** [comment]
You have to long press it (the ADV button), in order to get to the edit screen. I believe this has been the behaviour before as well.

**Comment by Karena-valentine** [comment]
This was not the behavior before; it was a normal press. I've been using
this software for many years, and have edited my presets several times. The
long press worked - thank you!

____________________________________
*Karena Valentine *(she/her)

1123 S. 48th Street Philadelphia, Pennsylvania 19143
c: 215.680.0026
Follow me on Instagram *@karenacreates @karenagardens*

**Comment by tzugen** [comment]
Fixed in 5.3.9
