### ISSUE TITLE
Red color alarming

### ISSUE THREAD

**Issue by Karena-valentine** [yuttadhammo/BodhiTimer#27]
Part of this app's legacy, and what sets it apart from the other timer/ meditation apps out there, was the aesthetic, and in particular that it used simple but soothing colors (black, white, and green), all the way down to the logo/ icon and timer background. The introduction of red is jarring, and inconsistent with the app's legacy and aesthetic language.

**Comment by tzugen** [comment]
You're right. I changed it back, the update will be out in a few days.

**Comment by Karena-valentine** [comment]
Thanks so much for your consideration on this!

____________________________________
*Karena Valentine *(she/her)

1123 S. 48th Street Philadelphia, Pennsylvania 19143
c: 215.680.0026
Follow me on Instagram *@karenacreates @karenagardens*
