### ISSUE TITLE
Unhappy with new version

### ISSUE THREAD

**Issue by bxgpsy** [yuttadhammo/BodhiTimer#30]
Please go back to original timer, this really sucks, It is unusable now thanks alot!

**Comment by tzugen** [comment]
Hey :) Could you write more in Detail what doesnt work for you?

**Comment by bxgpsy** [comment]
Just put it back the way it was, no changes were needed.

**Comment by yuttadhammo** [comment]
The old version was very much outdated and had several issues that were fixed in the latest version. If you have problems with the app as it exists now, you'll have to specify, because it's never going back to the old version.

**Comment by bxgpsy** [comment]
Look, I've already moved on, good luck!
