### ISSUE TITLE
Timer Sound change doesn't come  into effect

### ISSUE THREAD

**Issue by twisteros** [yuttadhammo/BodhiTimer#36]
1. Launch the app
2. Tap three dots
3. Tap Timer Sound
4. Tap Singing Bowl Low
5. Leave Preferences
6. Start timer and wait till the end 
7. Issue: The default sound is played rather than the one picked in Pt 4

**Comment by tzugen** [comment]
Is it the same after restarting the app?
And which version are you using.

**Comment by twisteros** [comment]
1. yes, the same
2. 5.5.2

**Comment by tzugen** [comment]
I can't reproduce it. Try updating to version 5.6.1 or 5.6.2 and see if its fixed there.
Otherwise it might be a race condition with the preferences, sometimes Android seems to return old preference values for a while..

**Comment by tzugen** [comment]
By restarting i meant force quitting the app.

**Comment by twisteros** [comment]
I downloaded the latest version and it's working fine
The issue has gone
Thank you!

**Comment by tzugen** [comment]
Great!
