### ISSUE TITLE
Customize vibration (Feature Request)

### ISSUE THREAD

**Issue by xilixi** [yuttadhammo/BodhiTimer#4]
First of all, I want to thank you for this awesome app! I use it almost everyday, and am really happy with it.

And now a request: I would like to use the app during the day: walking, watching TV, reading, ... And sometimes it's better to use vibration, for not disturbing anybody nor attracting attention. In vibration mode you may get confused with a message or whatever vibration. So...

Could you enable vibration customization? (For example: 3 long vibrations in a row), in such way that you know for sure that it is the app what it is calling your attention.

Thank you very much!

**Comment by tzugen** [comment]
With the new Android Notifications there is less room for the app to customize. 
I will implement a setting to activate do not disturb when meditating, then also you should know that the vibration came from the app.
