### ISSUE TITLE
Android version 11

### ISSUE THREAD

**Issue by Dhammadipa** [yuttadhammo/BodhiTimer#40]
I like the timer a lot. After my latest android 11 update it dadly will not start any more.
Kind regards
Marc

**Comment by tzugen** [comment]
Is there any error shown?

**Comment by Dhammadipa** [comment]
I get a message saying " bohdi timer keeps stopping"

Op zaterdag 10 april 2021 schreef tzugen ***@***.***>:

**Comment by tzugen** [comment]
I just pushed an update to F-Droid with version 6.0.0
It should appear in a day or two. If there are no complains I will release it to G-Play
