### ISSUE TITLE
Preparation time setting in the preferences does not work

### ISSUE THREAD

**Issue by Sunspark-007** [yuttadhammo/BodhiTimer#52]
Version 5.6.2

Issue: Setting this to any numeric value has no effect.

Expected behaviour: The defined delay interval to count off before beginning the main timer cycle whether on repeat or single-run.

**Comment by tzugen** [comment]
Can you try to re-set the main timer after you set the preparation time?

**Comment by Sunspark-007** [comment]
Certainly, I set the prep time to a new value then went to the upper left and set a new main time as well. It started counting with no delay, and when it got to the end it repeated the main timer (I have it on repeat) with no prep time delay either. This device is on Android 9.

**Comment by Sunspark-007** [comment]
The newest update 6.0.0 continues to not have a working preparation timer in the options. You can set it to any number you want, it will not insert the delay and will immediately re-start the main timer.

**Comment by tzugen** [comment]
I think maybe it only works if you set a Beginning Tone as well. Can you check?

**Comment by tzugen** [comment]
Fixed
