### ISSUE TITLE
Feature Request: Material Design Time Picker

### ISSUE THREAD

**Issue by metasean** [yuttadhammo/BodhiTimer#6]
First - I love BodhiTimer! - Job well done!

Second - One of the things I love about BodhiTimer is the visual simplicity and the simplicity in usage.  I just needed to set a new time, and realized how onerous the standard timepicker is in most systems, including BodhiTimer.  For a long time, I've thought there must be a better way to input times, but until I encountered a Material Design time picker, I had no idea what that better way might be.  

The point being, a Material Design time picker would actually align much better with the visual simplicity and the simplicity of BodhiTimer's usage than the current time picker. 

http://www.material-ui.com/#/components/time-picker

**Comment by tzugen** [comment]
Fixed in 5.1.0  :+1:
