### ISSUE TITLE
Timer Tone at the end is missing.

### ISSUE THREAD

**Issue by EduardoG26** [yuttadhammo/BodhiTimer#7]
Hallo.
First of all I like your timer very much. It's just what I was looking for. Very beautiful.
Since I changed to a new smartphone, WIKO, Android 6.0, the tone at the end of the time interval is missing. The start tone is ok. I have tested all kinds of tones.
Thanks for your help.
Regards.
Eduardo

**Comment by tzugen** [comment]
Should be fixed with 5.1.0.
If it still happens please reopen with information on which timers you set (how long etc)
