### ISSUE TITLE
Tapping notification does nothing

### ISSUE THREAD

**Issue by dalb8** [yuttadhammo/BodhiTimer#82]
In many apps, tapping the notification would bring you back to the app. In the current behaviour, one is obliged to go through many steps to restart the timer.

**Comment by tzugen** [comment]
@tumashu Can you reproduce this?

**Comment by tumashu** [comment]
@tzugen  In my phone, when timer is running,  notification will be showed, when timer is stop, notification will not show. always show notification option seem to no effect.

**Comment by tumashu** [comment]
@tzugen yes，it can

**Comment by tumashu** [comment]
```
when timer is stop, notification will not show. 
```
When I reboot my phone, this seem work.
