### ISSUE TITLE
Auto-Restart do not work when use back botton hide

### ISSUE THREAD

**Issue by tumashu** [yuttadhammo/BodhiTimer#88]
When I set Auto-Restart Timer enable,  if I hide BodhiTimer with android back botton, timer will be not auto restart,
is this a feature or bug?

**Comment by tzugen** [comment]
This sounds like a bug. Thanks for the translation.
I will release a minor version in the next days, then the translations should be synced again!

**Comment by tumashu** [comment]
@tzugen is it possible fixed?  this bug is very confusing，I found it after testing for a long time
