### ISSUE TITLE
Translate ui to Chinese.

### ISSUE THREAD

**Issue by tumashu** [yuttadhammo/BodhiTimer#89]
I would like translate bodhitimer to Chinese, and I have sent the join requests, thanks!

**Comment by tzugen** [comment]
You should be able to start now!

**Comment by tzugen** [comment]
Hi, I have synced with Transifex, you should be able to translate the Notification strings now

**Comment by tumashu** [comment]
@tzugen ok, finished!

**Comment by tumashu** [comment]
@tzugen I have updated Chinese translation today, please include it in next version, thanks!

**Comment by tumashu** [comment]
@tzugen Update Chinese again, please include it in next version, thanks!
