### ISSUE TITLE
Show better error if Google app not installed

### ISSUE THREAD

**Issue by dalb8** [yuttadhammo/BodhiTimer#9]
When trying a voice search without having the Google app installed the app trys to open https://play.google.com/store/apps/details?id=com.google.android.voicesearch. Such an app doesn't exist anymore; the voice functionality is within the Google app.

 Since it is unlikely that somebody would have a phone that has the Play Store but not the Google app; and quite possible that that person has neither installed, a more generic notice should be provided.

**Comment by tzugen** [comment]
Does the voice fnctionality work, when the Google app is installed?

**Comment by dalb8** [comment]
yes it works
