### ISSUE TITLE
Circle carton's color is not good in dark mode when update to version 6.1.0

### ISSUE THREAD

**Issue by tumashu** [yuttadhammo/BodhiTimer#91]
![Screenshot_20221112_081403_org yuttadhammo BodhiTimer](https://user-images.githubusercontent.com/67725/201446681-b57977d6-d461-46e7-b903-c1eb2f6fabea.jpg)

**Comment by tzugen** [comment]
So the circle is not white? Weird is is here...

- What device are you using
- Which android version
- Which theme: Day and Night or Dark?

Have you force quit the app and restarted? It is still the same?

**Comment by tumashu** [comment]
huawei phone, harmonyOS 2.0.0, dark theme, do you mean the color of circle in yor phone is white?

**Comment by tzugen** [comment]
Fixed.
Also updated the localization
