### ISSUE TITLE
Version 6.1.0 crashes and is unusable

### ISSUE THREAD

**Issue by Solomon1732** [yuttadhammo/BodhiTimer#92]
Since the update to 6.1.0 I can't use the app. It crashes the instant I try to start a session, change an option, or change the timer. I tried to delete its app cache and app data, and to uninstall and reinstall. Nothing seems to work. If it has a logging feature, I don't know how to find it.

**Comment by tzugen** [comment]
Oh no this is not good!
Have you installed from Fdroid or GPlay?
Which device are you using?
What is your Android version?

**Comment by Solomon1732** [comment]
I forgot to supply details! My bad. Fdroid, Samsung A73, Android 12. Erm, anything more from my phone's About Phone section?

**Comment by tzugen** [comment]
Ok, you should be able to install an older version on Fdroid if you open the versions section.
There is no setting yet to output the logs to a file. Do you happen to have `adb` installed on your computer?

**Comment by Solomon1732** [comment]
I'll install the one before last. I don't have `adb`. I also can't run it properly: my computer's OS makes handling it a major pain

**Comment by tzugen** [comment]
Ok, sorry for the trouble! I will include a logging feature in the next release, then i should be able to figure out what went wrong!

**Comment by Solomon1732** [comment]
No no, it's fine! You develop it. The least I could do is provide as many details as I can. For now I'll downgrade and wait for the next release

**Comment by tzugen** [comment]
I think I figured it out. 
Version 6.1.1 should be available around tomorrow

**Comment by aselker** [comment]
I got this also, on a Samsung Galaxy A32 on Android 12.  I've got `adb` set up, if you still want logs or something!

**Comment by chri-bra** [comment]
Hi tzugen
On my Google Pixel 6 the app also crashes. This is the logcat log.
[logcat.txt](https://github.com/yuttadhammo/BodhiTimer/files/10015603/logcat.txt)

I also recognized that there are predefined values missing in the new version. See screenshots
![Screenshot_20221113-081837](https://user-images.githubusercontent.com/77125749/202007571-d121b946-5b28-4a8b-b268-66905d995f47.png)
![Screenshot_20221113-081703](https://user-images.githubusercontent.com/77125749/202007581-8357cfff-9d30-46e4-9cdf-0a5d477b3ae7.png)

best regards
Christian

**Comment by Solomon1732** [comment]
I tried version 6.1.1. It still crashes in the same ways version 6.1.0 does 😅

**Comment by aselker** [comment]
> > I've got this also (6.0 works, 6.1 crashes), on a Samsung Galaxy A32 on Android 12. I've got `adb` set up, if you still want logs or something!
> 
> If its no problem, connect your device to your pc, run `adb logcat` in the terminal, and then trigger the crash, and copy the output from logcat here :)

Emailed!

**Comment by tzugen** [comment]
Hei, 
so I didn't even know that the app had so many users :)
I just pushed 6.1.2 which now fixes the crash which showed up in the adb log. 
With 6.1.1 I was guessing in the dark, and removed a potential source of crash, but not the right one :)

**Comment by Solomon1732** [comment]
I'll update when it lands in f-droid

**Comment by Solomon1732** [comment]
It works now. Thanks for the fix 😃
