### ISSUE TITLE
App crash on timer start

### ISSUE THREAD

**Issue by MrJberg** [yuttadhammo/BodhiTimer#99]
Running Bodhi Timer on OnePlus 9 Pro with Android 13 English the app crashes when starting the timer.

Bodhi Timer version 6.1.1

I've tried 
* uninstalling and reinstalling the app
* clearing the cash and all data related to the app
* changing settings to use old notification

Note: "Allow notification" setting is not available for Bohdi timer, in the app settings in the system settings.

I'll be happy to help testing any bugfixes.

Finally, the contact details for the app should probably be updated.

**Comment by Solomon1732** [comment]
It relates to #92

**Comment by tzugen** [comment]
Can you check if it is gone with the version 6.1.2, which is now available on F-Droid?

**Comment by MrJberg** [comment]
Just checked and version 6.1.2 works. 

Thanks and keep up the great work. 

#Stefan
-----------------------------------
Stefan Jernberg
***@***.***
+46 739 128 622
-----------------------------------
“Dwell on the beauty of life. Watch the stars, 
and see yourself running with them.” 
- Marcus Aurelius
